# Use Starter
# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml#L5

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: |
        npm ci
        npm build
        npm test